FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files into the container
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY data .

# Set default command
#CMD ["python", "main.py"]
